# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftNews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftNews
  pod 'RxSwift', '~> 4'
  pod 'RxCocoa', '~> 4'

  target 'RxSwiftNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftNewsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
